config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('pages.urls',namespace='index')),
    path('admin/', admin.site.urls),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

pages/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'pages/index.html')

def about(request):
    return render(request, 'pages/about.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href={% static "css/all.css" %} />
    <!-- Bootstrap -->
    <link rel="stylesheet" href={% static "css/bootstrap.css" %} />
    <link rel="stylesheet" href={% static "css/lightbox.min.css" %} />
    <!-- Custom -->
    <link rel="stylesheet" href={% static "css/style.css" %} />
    <link rel="icon" href={% static "img/logo.png" %} />
    <title>BBN Community</title>
  </head>

  <body>
    {% include 'partials/_topbar.html'%}
    {% include 'partials/_navbar.html' %}
    {% block content %}{% endblock %}
    {% include 'partials/_footer.html' %}

    <script src={% static "js/jquery-3.3.1.min.js" %} ></script>
    <script src={% static "js/bootstrap.bundle.min.js" %} ></script>
    <script src={% static "js/lightbox.min.js" %} ></script>
    <script src={% static "js/main.js" %} ></script>
  </body>
</html>

templates/pages/about.html
{% extends "base.html" %} {% load static %}
{% block content %}

    <section id="showcase-inner" class="py-5 text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1 class="display-4">About Blooms and Blossom Neigborhood Community</h1>
            <p class="lead">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
              pariatur!
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
      <div class="container">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href={%url "pages:index"%}> <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item active">About</li>
          </ol>
        </nav>
      </div>
    </section>

    <section id="about" class="py-4">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <h2>
              We Search For The Your health, your home – we help you find the
              right clinic.
            </h2>
            <p class="lead">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
              pariatur!
            </p>
            <img src={% static "img/about.jpg"%} alt="" />
            <p class="mt-4">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Perspiciatis esse officia repudiandae ad saepe ex, amet neque quod
              accusamus rem quia magnam magni dolorum facilis ullam minima
              perferendis? Exercitationem at quaerat commodi id libero eveniet
              harum perferendis laborum molestias quia.
            </p>
          </div>
          <div class="col-md-4">
            <div class="card">
                {% comment %}  {% endcomment %}
              <img
                class="card-img-top"
                src={% static "img/doctors/kyle.jpg"%}
                alt="Seller of the month"
              />
              <div class="card-body">
                <h5 class="card-title">Top Doctor</h5>
                <h6 class="text-secondary">Kyle chan</h6>
                <p class="card-text">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis
                  nesciunt amet, illo itaque similique repellat. content.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Work -->
    <section id="work" class="bg-dark text-white text-center">
      <h2 class="display-4">We Work For You</h2>
      <h4>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit
        aperiam, unde aliquid at similique!
      </h4>
      <hr />
      {% comment %}  {% endcomment %}
      <a href="listings.html" class="btn btn-secondary text-white btn-lg"
        >View Our Featured Listings</a
      >
    </section>

    <!-- Team -->
    <section id="team" class="py-5">
      <div class="container">
        <h2 class="text-center pb-4">Our Team</h2>
        <div class="row text-center">
          <div class="col-md-4">
            {% comment %}  {% endcomment %}
            <img
              src={% static "img/doctors/kyle.jpg"%}
              alt=""
              class="rounded-circle mb-3 img-fluid"
              style="object-fit: cover; width: 300px; height: 300px"
            />
            <h4>Kyle Chan</h4>
            <p class="text-success">
              <i class="fas fa-award text-success"></i> Doctor
            </p>
            <hr />
            <p><i class="fas fa-phone"></i> (852)2711-98205</p>
            <p><i class="fas fa-envelope-open"></i> kyle@healthcare.co</p>
          </div>

          <div class="col-md-4">
            {% comment %}  {% endcomment %}
            <img
              src={% static "img/doctors/emma.jpg"%}
              alt=""
              class="rounded-circle mb-3 img-fluid"
              style="object-fit: cover; width: 300px; height: 300px"
            />
            <h4>Emma Lee</h4>
            <p class="text-success">Doctor</p>
            <hr />
            <p><i class="fas fa-phone"></i> (852)-444-4444</p>
            <p><i class="fas fa-envelope-open"></i> emma@healthcare.co</p>
          </div>

          <div class="col-md-4">
            {% comment %}  {% endcomment %}
            <img
              src={% static "img/doctors/jenny.jpg"%}
              alt=""
              class="rounded-circle mb-3 img-fluid"
              style="object-fit: cover; width: 300px; height: 300px"
            />
            <h4>Jenny Cheung</h4>
            <p class="text-success">Doctor</p>
            <hr />
            <p><i class="fas fa-phone"></i> (852)-333-3333</p>
            <p><i class="fas fa-envelope-open"></i> jenny@healthcare.co</p>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

templates/pages/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>index.html</h1>
{% endblock content %}

templates/partials/_footer.html
{% load static %}
    <!-- Footer -->
    <footer id="main-footer" class="py-4 text-white text-center" style="background-color:purple;"> 
      Copyright &copy;
      <span class="year"></span> Blooms and Blossom Neighborhood Community
    </footer>

templates/partials/_navbar.html
{% load static %}
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: purple;">
      <div class="container">
        {% comment %}  {% endcomment %}
        <a class="navbar-brand" href={% url "pages:index"%}>
          <img src={%static "img/logo.png"%} class="logo" alt="" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav">            
            <li {% if '/' == request.path %} class="nav-item active mr-3" {%else%} class="nav-item mr-3" {%endif%}>
              <a class="nav-link" href={%url "pages:index"%}>Home</a>
            </li>
            <li class="nav-item mr-3">
              <a class="nav-link" href={%url "pages:about"%}>About</a>
            </li>
            <li class="nav-item mr-3">
              {% comment %}  {% endcomment %}
              <a class="nav-link" href="products.html">Products</a>
            </li>
            <li class="nav-item mr-3">
              {% comment %}  {% endcomment %}
              <a class="nav-link" href="reviews.html">Reviews</a>
            </li>
            <li class="nav-item mr-3">
              {% comment %}  {% endcomment %}
              <a class="nav-link" href="services.html">Services</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-3">
              {% comment %}  {% endcomment %}
              <a class="nav-link" href="register.html">
                <i class="fas fa-user-plus"></i> Register</a
              >
            </li>
            <li class="nav-item mr-3">
              {% comment %}  {% endcomment %}
              <a class="nav-link" href="login.html">
                <i class="fas fa-sign-in-alt"></i>

                Login</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

templates/partials/_topbar.html
{% load static %}
    <!-- Top Bar -->
    <section id="top-bar" class="p-3">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <i class="fas fa-phone"></i> (852)2711-98205
          </div>
          <div class="col-md-4">
            <i class="fas fa-envelope-open"></i> contact@hkctsvt.edu.hk
          </div>
          <div class="col-md-4">
            <div class="social text-right">
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#">
                <i class="fab fa-facebook"></i>
              </a>
              <a href="#">
                <i class="fab fa-linkedin"></i>
              </a>
              <a href="#">
                <i class="fab fa-instagram"></i>
              </a>
              <a href="#">
                <i class="fab fa-pinterest"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>

templates/products/products.html
{% extends "base.html" %} {% load static %}
{% block content %}
<h1>product.html</h1>
{% endblock content %}